/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include "../MCAL/RCC/inc/RCC_interface.h"
#include "../MCAL/GPIO/inc/GPIO_interface.h"
#include "../MCAL/SYSTICK/inc/SysTick_interface.h"
#include "../HAL/LED/inc/led_interface.h"
#include "../HAL/LCD/inc/LCD_interface.h"
#include "../HAL/SEVEN_SEG/inc/sev_seg_interface.h"

/***********************
     * led program *
 ***********************/
/*
int main(void)
{

	ST_RCC_Config_t user_rcc =
	{
			.Sys_Clk_Select = HSI_system_clock_select ,
			.PLL_clk_src = Half_HSI,
			.PLL_Factor = PLL_input_clock_x2 ,
			.AHP_Pres = AHP_SYSCLK_not_devided ,
			.APB1_Pres = APB1_HCLK_not_divided ,
			.APB2_Pres = APB2_HCLK_not_divided
	};

	ST_Pin_Config led_pin =
	{
			.Port_X = PORTC ,
			.Pin_Num = PIN13 ,
			.mode = OUTPUT_PUSH_PULL,
			.speed = MAX_PIN_2_MHZ
	};
	RCC_Config(&user_rcc);
	RCC_Enable_Peripheral(IOPCEN) ;
	GPIO_u8PIN_init(&led_pin);

	GPIO_u8Set_Pin_Value( PORTC ,PIN13 , PIN_HIGH);


	for(;;);
}
*/

/***********************
     * led program with init func *
 ***********************/
/*
int main()
{
	led_pin_init_clk(PORTC, PIN13);
	led_pin_init(PORTC, PIN13);

	uint16_t count = 200;
	for (;;)
	{
		if(count < 10)
		{
			{
				count = 200 ;
			}
		}
		else
		{

		led_On(PORTC, PIN13);

		SysTick_Delay_ms(count);

		led_Off(PORTC, PIN13);

		SysTick_Delay_ms(count);

		count = count - 5;
		}
	}
}

*/


/***********************
     * lcd program *
 ***********************/

int main()
{
	led_pin_init_clk(PORTC, PIN13);
	led_pin_init(PORTC, PIN13);

	lcd_clk_init();
	lcd_pins_init();

	lcd_init();

	lcd_data('B') ;
	lcd_data('V') ;
	lcd_data('H') ;

	for(;;)
	{
	}
}


/***********************
     * seven segment program *
 ***********************/
/*
int main()
{
	seven_seg_clk_init();
	seven_seg_pins_init();
	seven_seg_write_digit1(0);
	pulling_Delay_ms(50);
	seven_seg_write_digit1(5);
	uint8_t x = 0;
	for (;;)
	{

			if (x >= 10)
			{
				x = 0;
			}
			seven_seg_write_digit1(x);
			pulling_Delay_ms(500);
			x++;
	}
}

*/









